name: greatbrands_blott_mobile
description: "A Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.19.0
  one_context: ^4.0.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  icons_launcher: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/blott.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
